version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
      POSTGRES_PORT: ${TYPEORM_PORT}
      POSTGRES_HOST: ${TYPEORM_HOST}